### ISSUE TITLE
直接打开 exe 程序报错 2.0.3 版本

### ISSUE THREAD

**Issue by vvandk** [glyh/JavSPn#11]
### 问题详情

直接打开 exe 程序报错 2.0.3 版本

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 日志

无

### 运行截图（可选）

![image](https://github.com/glyh/JavSPn/assets/108704266/c3daaa54-cf3e-4304-a84d-faf9ae310194)

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by glyh** [comment]
请试下2.0.4

**Comment by vvandk** [comment]
2.0.4可以正常启动，感谢
